format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_memory}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_MEMORY_COMMON_FS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: 'true'}
  - type: File
    attributes: {id: DRV_MEMORY_FS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_memory}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_MEMORY_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: DRV_MX25L}
      - type: Comment
        attributes: {id: DRV_MEMORY_DEVICE_COMMENT}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: text}
            children:
            - {type: Value, value: '*** Configure Memory Device in DRV_MX25L Configurations
                ***'}
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Combo
        attributes: {id: DRV_MEMORY_DEVICE_TYPE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_ERASE_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_FS_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_INTERRUPT_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'false'}
      - type: Integer
        attributes: {id: DRV_MEMORY_NUM_CLIENTS}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '2'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_memory_MEMORY_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_mx25l}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: memory}
- type: ElementPosition
  attributes: {x: '185', y: '364', id: drv_memory}
