format_version: v1.0
configName: sam_a5d2_xult_freertos
folderName: sam_a5d2_xult_freertos
frameworkPath: C:\microchip\h3
processor: ATSAMA5D27
projectName: sam_a5d2_xult_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMA5D2_DFP\1.7.91\atdf\ATSAMA5D27.atdf
