configName: sam_a5d2_xplained_ultra_MPLABX
folderName: sam_a5d2_xplained_ultra_MPLABX
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAMA5D21
projectName: sam_a5d2_xplained_ultra_MPLABX
settings:
  PackageFilter: audio;azure_rtos;bsp;bt;core;crypto;cryptoauthlib;crypto_for_4.8.1;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2;dev_packs;gfx;motor_control;net;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_9x60;net_apps_sam_a5d2;net_apps_sam_e5x;net_apps_sam_e70_v71;net_apps_sam_rh71;quick_docs;usb;wireless;wireless_wifi;zzz_expresslogic_threadx
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.6.69\atdf\ATSAMA5D21.atdf
