format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIperf}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_IPERF_RX_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8192'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TX_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8192'}
  - type: Integer
    attributes: {id: TCPIP_IPERF_TX_BW_LIMIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '100'}
- type: ElementPosition
  attributes: {x: '472', y: '146', id: tcpipIperf}
