format_version: v1.0
type: UniqueComponent
attributes: {id: qspi0}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: QSPI_CLK_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** QSPI Clock Frequency Is Set To 33.2 MHz for Master
            Clock Frequency At 166.0 MHz'}
  - type: Integer
    attributes: {id: QSPI_CLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '33200000'}
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '0'}
  - type: Integer
    attributes: {id: QSPI_SCBR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: KeyValueSet
    attributes: {id: QSPI_SMM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi0, value: '0'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: QSPI0_SQI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_mx25l}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_mx25l_SQI_dependency}
- type: ElementPosition
  attributes: {x: '8', y: '456', id: qspi0}
