format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipHttpNet}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_HTTP_NET_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: 'true'}
- type: ElementPosition
  attributes: {x: '330', y: '120', id: tcpipHttpNet}
